package com.rozhak.imageoptimize.core.network.interceptor

import com.rozhak.imageoptimize.core.network.exception.AppException
import okhttp3.Interceptor
import okhttp3.Response
import okhttp3.internal.parseCookie
import org.json.JSONObject
import java.io.IOException

/**
 * Global HTTP Interceptor that enforces the JSend protocol and centralizes error handling.
 * Traps raw HTTP status codes and maps them into strongly-typed [AppException] models.
 */
class JSendInterceptor : Interceptor {
    /**
     * Intercepts outgoing requests and evaluates incoming responses.
     * Extracts structured error messages natively generated by FastAPI if the request fails.
     *
     * @param chain The OkHttp interceptor chain.
     * @return The original [Response] if HTTP code is 2xx.
     * @throws AppException specific subtypes (e.g. NetworkError, ValidationError) to be caught by the repository layer.
     */
    override fun intercept(chain: Interceptor.Chain): Response {
        val request = chain.request()
        val response: Response = try {
            chain.proceed(request)
        } catch (e: IOException) {
            throw AppException.NetworkError()
        }

        if (!response.isSuccessful) {
            val errorBodyString = response.body?.string() ?: ""
            response.close()

            when (response.code) {
                400, 413 -> throw AppException.ClientError(parseJSendMessage(errorBodyString))
                422 -> throw AppException.ValidationError(parseFastApiValidationError(errorBodyString))
                500 -> throw AppException.ServerError(parseJSendMessage(errorBodyString))
                else -> throw AppException.UnknownError("HTTP_FAULT_${response.code}")
            }
        }
        return response
    }

    /**
     * Decodes the standard JSend format to extract the 'message' node.
     */
    private fun parseJSendMessage(json: String): String {
        return try {
            JSONObject(json).getString("message")
        } catch (e: Exception) {
            "ERR_UNKNOWN_PAYLOAD"
        }
    }

    /**
     * Decodes FastAPI's specific 422 Unprocessable Entity array structure.
     * Targets the first 'detail' item to extract the precise field and validation error.
     */
    private fun parseFastApiValidationError(json: String): String {
        return try {
            val detailArray = JSONObject(json).getJSONArray("detail")
            if (detailArray.length() > 0) {
                val firstError = detailArray.getJSONObject(0)
                val field = firstError.getJSONArray("loc").getString(1)
                val msg = firstError.getString("msg")
                "ERR_VALIDATION: Parameter '$field' -> $msg"
            } else {
                "ERR_VALIDATION: Invalid Input"
            }
        } catch (e: Exception) {
            "ERR_VALIDATION_FORMAT_FAILED"
        }
    }
}
